// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using UIdea.Models;

namespace UIdea.Migrations
{
    [DbContext(typeof(UIdeaContext))]
    [Migration("20180521085922_IdeaAvatarImage")]
    partial class IdeaAvatarImage
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UIdea.Models.Idea", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("AvatarImage");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<string>("EmailContact");

                    b.Property<string>("FacebookContact");

                    b.Property<string>("GitHubContact");

                    b.Property<string>("InstagramContact");

                    b.Property<string>("LinkedinContact");

                    b.Property<string>("Members");

                    b.Property<string>("OtherContact");

                    b.Property<string>("OwnerID");

                    b.Property<string>("RequiredMembers")
                        .IsRequired();

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<string>("TwitterContact");

                    b.HasKey("ID");

                    b.ToTable("Idea");
                });
#pragma warning restore 612, 618
        }
    }
}
