// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using UIdea.Models;

namespace UIdea.Migrations
{
    [DbContext(typeof(UIdeaContext))]
    partial class UIdeaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UIdea.Models.Idea", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Members");

                    b.Property<string>("OwnerID");

                    b.Property<string>("RequiredMembers");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("Idea");
                });
#pragma warning restore 612, 618
        }
    }
}
